import type { PatientCase } from "./types";

export const DEMO_CASES: PatientCase[] = [
  {
    id: "case-ortopedie",
    label: "PTH — patient polymédiqué",
    patientInitials: "M. D.",
    age: 72,
    sex: "M",
    asa: "ASA III",
    procedure: "Prothèse totale de hanche droite",
    procedureDate: "2026-07-28",
    bleedingRisk: "élevé",
    anesthesiaType: "Rachianesthésie ± sédation",
    comorbidities: [
      "Fibrillation auriculaire",
      "HTA",
      "Diabète de type 2",
      "Stent coronaire > 12 mois",
    ],
    allergies: [
      {
        id: "a1",
        label: "Pénicilline",
        reaction: "Éruption cutanée (enfance)",
      },
    ],
    medications: [
      {
        id: "m1",
        name: "Apixaban",
        className: "Anticoagulant",
        dose: "5 mg × 2 / j",
        indication: "FA non valvulaire",
        decision: "non_renseigne",
        holdDays: "",
        resumeNote: "",
        clinicianNote: "",
      },
      {
        id: "m2",
        name: "Aspirine",
        className: "Antiagrégant",
        dose: "75 mg / j",
        indication: "Prévention secondaire coronaire",
        decision: "non_renseigne",
        holdDays: "",
        resumeNote: "",
        clinicianNote: "",
      },
      {
        id: "m3",
        name: "Metformine",
        className: "Antidiabétique",
        dose: "850 mg × 2 / j",
        indication: "Diabète de type 2",
        decision: "non_renseigne",
        holdDays: "",
        resumeNote: "",
        clinicianNote: "",
      },
      {
        id: "m4",
        name: "Bisoprolol",
        className: "Antihypertenseur",
        dose: "2,5 mg / j",
        indication: "HTA / rythme",
        decision: "non_renseigne",
        holdDays: "",
        resumeNote: "",
        clinicianNote: "",
      },
      {
        id: "m5",
        name: "Ramipril",
        className: "Antihypertenseur",
        dose: "5 mg / j",
        indication: "HTA",
        decision: "non_renseigne",
        holdDays: "",
        resumeNote: "",
        clinicianNote: "",
      },
    ],
    airwayNotes: "",
    cardioNotes: "",
  },
  {
    id: "case-chirurgie-digestive",
    label: "Cholécystectomie — bithérapie",
    patientInitials: "Mme L.",
    age: 58,
    sex: "F",
    asa: "ASA II",
    procedure: "Cholécystectomie laparoscopique",
    procedureDate: "2026-08-04",
    bleedingRisk: "intermédiaire",
    anesthesiaType: "Anesthésie générale",
    comorbidities: ["Coronarien récent (stent à 4 mois)", "Dyslipidémie"],
    allergies: [],
    medications: [
      {
        id: "m1",
        name: "Clopidogrel",
        className: "Antiagrégant",
        dose: "75 mg / j",
        indication: "Bithérapie post-stent",
        decision: "non_renseigne",
        holdDays: "",
        resumeNote: "",
        clinicianNote: "",
      },
      {
        id: "m2",
        name: "Aspirine",
        className: "Antiagrégant",
        dose: "75 mg / j",
        indication: "Bithérapie post-stent",
        decision: "non_renseigne",
        holdDays: "",
        resumeNote: "",
        clinicianNote: "",
      },
      {
        id: "m3",
        name: "Atorvastatine",
        className: "Autre",
        dose: "40 mg / j",
        indication: "Dyslipidémie",
        decision: "non_renseigne",
        holdDays: "",
        resumeNote: "",
        clinicianNote: "",
      },
      {
        id: "m4",
        name: "Pantoprazole",
        className: "Autre",
        dose: "40 mg / j",
        indication: "Protection gastrique",
        decision: "non_renseigne",
        holdDays: "",
        resumeNote: "",
        clinicianNote: "",
      },
    ],
    airwayNotes: "",
    cardioNotes: "",
  },
];

export function getCaseById(id: string): PatientCase | undefined {
  return DEMO_CASES.find((c) => c.id === id);
}
